/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface PearInput {
        "disabled": boolean;
        "floatLabel": boolean;
        "focused": boolean;
        "hasError": boolean;
        "label": string;
        "labelFor": string;
    }
}
declare global {
    interface HTMLPearInputElement extends Components.PearInput, HTMLStencilElement {
    }
    var HTMLPearInputElement: {
        prototype: HTMLPearInputElement;
        new (): HTMLPearInputElement;
    };
    interface HTMLElementTagNameMap {
        "pear-input": HTMLPearInputElement;
    }
}
declare namespace LocalJSX {
    interface PearInput {
        "disabled"?: boolean;
        "floatLabel"?: boolean;
        "focused"?: boolean;
        "hasError"?: boolean;
        "label"?: string;
        "labelFor"?: string;
    }
    interface IntrinsicElements {
        "pear-input": PearInput;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "pear-input": LocalJSX.PearInput & JSXBase.HTMLAttributes<HTMLPearInputElement>;
        }
    }
}
